// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: judgements.proto

package protobuf_spec

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProblemId    string `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	SubmissionId uint64 `protobuf:"varint,3,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	JudgementId  uint64 `protobuf:"varint,4,opt,name=judgement_id,json=judgementId,proto3" json:"judgement_id,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *ListRequest) GetSubmissionId() uint64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *ListRequest) GetJudgementId() uint64 {
	if x != nil {
		return x.JudgementId
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{1}
}

type Argument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Argument) Reset() {
	*x = Argument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{2}
}

func (x *Argument) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Argument) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{3}
}

func (x *Slot) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Slot) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CreateJudgementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubmissionId uint64      `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Type         string      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Arguments    []*Argument `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Slots        []*Slot     `protobuf:"bytes,4,rep,name=slots,proto3" json:"slots,omitempty"`
}

func (x *CreateJudgementRequest) Reset() {
	*x = CreateJudgementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJudgementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJudgementRequest) ProtoMessage() {}

func (x *CreateJudgementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJudgementRequest.ProtoReflect.Descriptor instead.
func (*CreateJudgementRequest) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{4}
}

func (x *CreateJudgementRequest) GetSubmissionId() uint64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *CreateJudgementRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateJudgementRequest) GetArguments() []*Argument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CreateJudgementRequest) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type CreateJudgementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JudgementId string `protobuf:"bytes,1,opt,name=judgement_id,json=judgementId,proto3" json:"judgement_id,omitempty"`
}

func (x *CreateJudgementResponse) Reset() {
	*x = CreateJudgementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJudgementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJudgementResponse) ProtoMessage() {}

func (x *CreateJudgementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJudgementResponse.ProtoReflect.Descriptor instead.
func (*CreateJudgementResponse) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{5}
}

func (x *CreateJudgementResponse) GetJudgementId() string {
	if x != nil {
		return x.JudgementId
	}
	return ""
}

type PullJudgementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *PullJudgementRequest) Reset() {
	*x = PullJudgementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullJudgementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullJudgementRequest) ProtoMessage() {}

func (x *PullJudgementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullJudgementRequest.ProtoReflect.Descriptor instead.
func (*PullJudgementRequest) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{6}
}

func (x *PullJudgementRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PullJudgementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Arguments []*Argument `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Slots     []*Slot     `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
}

func (x *PullJudgementResponse) Reset() {
	*x = PullJudgementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullJudgementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullJudgementResponse) ProtoMessage() {}

func (x *PullJudgementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullJudgementResponse.ProtoReflect.Descriptor instead.
func (*PullJudgementResponse) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{7}
}

func (x *PullJudgementResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PullJudgementResponse) GetArguments() []*Argument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *PullJudgementResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type PushJudgementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Slots []*Slot `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
}

func (x *PushJudgementRequest) Reset() {
	*x = PushJudgementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushJudgementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushJudgementRequest) ProtoMessage() {}

func (x *PushJudgementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushJudgementRequest.ProtoReflect.Descriptor instead.
func (*PushJudgementRequest) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{8}
}

func (x *PushJudgementRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PushJudgementRequest) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type PushJudgementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
}

func (x *PushJudgementResponse) Reset() {
	*x = PushJudgementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_judgements_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushJudgementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushJudgementResponse) ProtoMessage() {}

func (x *PushJudgementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_judgements_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushJudgementResponse.ProtoReflect.Descriptor instead.
func (*PushJudgementResponse) Descriptor() ([]byte, []int) {
	return file_judgements_proto_rawDescGZIP(), []int{9}
}

func (x *PushJudgementResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_success
}

var File_judgements_proto protoreflect.FileDescriptor

var file_judgements_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x32, 0x0a, 0x08, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x75, 0x64,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x1b, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x17,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x75, 0x64, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a,
	0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x14, 0x50, 0x75,
	0x6c, 0x6c, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x73, 0x0a, 0x15, 0x50, 0x75, 0x6c, 0x6c, 0x4a, 0x75,
	0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1b,
	0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x22, 0x49, 0x0a, 0x14, 0x50,
	0x75, 0x73, 0x68, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x05, 0x73, 0x6c, 0x6f,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52,
	0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x15, 0x50, 0x75, 0x73, 0x68, 0x4a, 0x75,
	0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x32, 0x81, 0x02, 0x0a, 0x0a, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x2d, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x0c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44,
	0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x50, 0x75, 0x6c, 0x6c, 0x4a, 0x75, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4a, 0x75, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x50,
	0x75, 0x6c, 0x6c, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x4a, 0x75, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4a, 0x75, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_judgements_proto_rawDescOnce sync.Once
	file_judgements_proto_rawDescData = file_judgements_proto_rawDesc
)

func file_judgements_proto_rawDescGZIP() []byte {
	file_judgements_proto_rawDescOnce.Do(func() {
		file_judgements_proto_rawDescData = protoimpl.X.CompressGZIP(file_judgements_proto_rawDescData)
	})
	return file_judgements_proto_rawDescData
}

var file_judgements_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_judgements_proto_goTypes = []interface{}{
	(*ListRequest)(nil),             // 0: ListRequest
	(*ListResponse)(nil),            // 1: ListResponse
	(*Argument)(nil),                // 2: Argument
	(*Slot)(nil),                    // 3: Slot
	(*CreateJudgementRequest)(nil),  // 4: CreateJudgementRequest
	(*CreateJudgementResponse)(nil), // 5: CreateJudgementResponse
	(*PullJudgementRequest)(nil),    // 6: PullJudgementRequest
	(*PullJudgementResponse)(nil),   // 7: PullJudgementResponse
	(*PushJudgementRequest)(nil),    // 8: PushJudgementRequest
	(*PushJudgementResponse)(nil),   // 9: PushJudgementResponse
	(Status)(0),                     // 10: Status
}
var file_judgements_proto_depIdxs = []int32{
	2,  // 0: CreateJudgementRequest.arguments:type_name -> Argument
	3,  // 1: CreateJudgementRequest.slots:type_name -> Slot
	2,  // 2: PullJudgementResponse.arguments:type_name -> Argument
	3,  // 3: PullJudgementResponse.slots:type_name -> Slot
	3,  // 4: PushJudgementRequest.slots:type_name -> Slot
	10, // 5: PushJudgementResponse.status:type_name -> Status
	0,  // 6: Judgements.ListJudgements:input_type -> ListRequest
	4,  // 7: Judgements.CreateJudgement:input_type -> CreateJudgementRequest
	6,  // 8: Judgements.PullJudgement:input_type -> PullJudgementRequest
	8,  // 9: Judgements.PushJudgement:input_type -> PushJudgementRequest
	1,  // 10: Judgements.ListJudgements:output_type -> ListResponse
	5,  // 11: Judgements.CreateJudgement:output_type -> CreateJudgementResponse
	7,  // 12: Judgements.PullJudgement:output_type -> PullJudgementResponse
	9,  // 13: Judgements.PushJudgement:output_type -> PushJudgementResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_judgements_proto_init() }
func file_judgements_proto_init() {
	if File_judgements_proto != nil {
		return
	}
	file_status_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_judgements_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Argument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJudgementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJudgementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullJudgementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullJudgementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushJudgementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_judgements_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushJudgementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_judgements_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_judgements_proto_goTypes,
		DependencyIndexes: file_judgements_proto_depIdxs,
		MessageInfos:      file_judgements_proto_msgTypes,
	}.Build()
	File_judgements_proto = out.File
	file_judgements_proto_rawDesc = nil
	file_judgements_proto_goTypes = nil
	file_judgements_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JudgementsClient is the client API for Judgements service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JudgementsClient interface {
	ListJudgements(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	CreateJudgement(ctx context.Context, in *CreateJudgementRequest, opts ...grpc.CallOption) (*CreateJudgementResponse, error)
	PullJudgement(ctx context.Context, in *PullJudgementRequest, opts ...grpc.CallOption) (*PullJudgementResponse, error)
	PushJudgement(ctx context.Context, in *PushJudgementRequest, opts ...grpc.CallOption) (*PushJudgementResponse, error)
}

type judgementsClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgementsClient(cc grpc.ClientConnInterface) JudgementsClient {
	return &judgementsClient{cc}
}

func (c *judgementsClient) ListJudgements(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/Judgements/ListJudgements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgementsClient) CreateJudgement(ctx context.Context, in *CreateJudgementRequest, opts ...grpc.CallOption) (*CreateJudgementResponse, error) {
	out := new(CreateJudgementResponse)
	err := c.cc.Invoke(ctx, "/Judgements/CreateJudgement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgementsClient) PullJudgement(ctx context.Context, in *PullJudgementRequest, opts ...grpc.CallOption) (*PullJudgementResponse, error) {
	out := new(PullJudgementResponse)
	err := c.cc.Invoke(ctx, "/Judgements/PullJudgement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgementsClient) PushJudgement(ctx context.Context, in *PushJudgementRequest, opts ...grpc.CallOption) (*PushJudgementResponse, error) {
	out := new(PushJudgementResponse)
	err := c.cc.Invoke(ctx, "/Judgements/PushJudgement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgementsServer is the server API for Judgements service.
type JudgementsServer interface {
	ListJudgements(context.Context, *ListRequest) (*ListResponse, error)
	CreateJudgement(context.Context, *CreateJudgementRequest) (*CreateJudgementResponse, error)
	PullJudgement(context.Context, *PullJudgementRequest) (*PullJudgementResponse, error)
	PushJudgement(context.Context, *PushJudgementRequest) (*PushJudgementResponse, error)
}

// UnimplementedJudgementsServer can be embedded to have forward compatible implementations.
type UnimplementedJudgementsServer struct {
}

func (*UnimplementedJudgementsServer) ListJudgements(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJudgements not implemented")
}
func (*UnimplementedJudgementsServer) CreateJudgement(context.Context, *CreateJudgementRequest) (*CreateJudgementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJudgement not implemented")
}
func (*UnimplementedJudgementsServer) PullJudgement(context.Context, *PullJudgementRequest) (*PullJudgementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullJudgement not implemented")
}
func (*UnimplementedJudgementsServer) PushJudgement(context.Context, *PushJudgementRequest) (*PushJudgementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushJudgement not implemented")
}

func RegisterJudgementsServer(s *grpc.Server, srv JudgementsServer) {
	s.RegisterService(&_Judgements_serviceDesc, srv)
}

func _Judgements_ListJudgements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).ListJudgements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/ListJudgements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).ListJudgements(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judgements_CreateJudgement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJudgementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).CreateJudgement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/CreateJudgement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).CreateJudgement(ctx, req.(*CreateJudgementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judgements_PullJudgement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullJudgementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).PullJudgement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/PullJudgement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).PullJudgement(ctx, req.(*PullJudgementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judgements_PushJudgement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushJudgementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).PushJudgement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/PushJudgement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).PushJudgement(ctx, req.(*PushJudgementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Judgements_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Judgements",
	HandlerType: (*JudgementsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJudgements",
			Handler:    _Judgements_ListJudgements_Handler,
		},
		{
			MethodName: "CreateJudgement",
			Handler:    _Judgements_CreateJudgement_Handler,
		},
		{
			MethodName: "PullJudgement",
			Handler:    _Judgements_PullJudgement_Handler,
		},
		{
			MethodName: "PushJudgement",
			Handler:    _Judgements_PushJudgement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judgements.proto",
}
